
/*
LarQ Entry Point Script (0.0.1)
generated by larq/generate-entry-point

do not edit this file

source language:    coffee-script@11.6.3
source route:       ./../src/main.coffee
 */

(function() {
  var language, language_name, njs_path, route, source, source_js, source_map, target_route;

  language_name = 'coffee-script';

  njs_path = require('path');

  route = njs_path.join(__dirname, './../src/main.coffee');

  target_route = njs_path.join(__dirname, 'main.js');

  source = (require('fs')).readFileSync(route, 'utf-8');

  source_js = null;

  source_map = null;

  language = null;

  language = require(language_name);

  
source_js = language.compile( source, { 'bare': false, 'filename': route } )
;

  if (source_map != null) {
    console.log("source maps not yet supported");
  }

  module._compile(source_js, target_route);

}).call(this);
/****generated by https://github.com/loveencounterflow/larq****/